name: "Github Release"
author: "kuloud"
branding:
  icon: "git-branch"
  color: "gray-dark"
description: "Publish Github releases from an action"

inputs:
  title:
    description: "The title of the release"
    required: true
  tag_name:
    description: "The tag name for the release"
    required: false
  body:
    description: "The body text of the release"
    required: false
  draft:
    description: "Create a draft release"
    required: false
    default: 'false'
  prerelease:
    description: "Identify the release as a prerelease"
    required: false
    default: 'false'
  workdir:
    description: "Directory of the repository that should create the release"
    required: false
  generate_notes:
    description: "Automatically generate release notes"
    required: false
    default: 'false'
  notes:
    description: "Release notes to include"
    required: false
  notes_file:
    description: "File path containing release notes"
    required: false
  discussion_category:
    description: "GitHub Discussions category to create"
    required: false
  target:
    description: "Specify the target branch or commit for the release"
    required: false
  verify_tag:
    description: "Verify the tag exists before creating the release"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_TAG: ${{ inputs.tag_name }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_DRAFT: ${{ inputs.draft }}
        INPUT_PRERELEASE: ${{ inputs.prerelease }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_GENERATE_NOTES: ${{ inputs.generate_notes }}
        INPUT_NOTES: ${{ inputs.notes }}
        INPUT_NOTES_FILE: ${{ inputs.notes_file }}
        INPUT_DISCUSSION_CATEGORY: ${{ inputs.discussion_category }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_VERIFY_TAG: ${{ inputs.verify_tag }}