
name: Release
on: 
  push:
    branches: [ main ]
    # tags-ignore:
    #   - '*'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Create a Release
      uses: kuloud/Github-Release-Action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ github.sha }}

  release:
    runs-on: ubuntu-latest
    needs:
      - integration-test
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish new version
        run: |
          git config --global user.email "xkuloud@gmail.com"
          git config --global user.name "kuloud"
          git tag -fa v1 -m "Update v1 tag"
          git push origin v1 --force
